# Generated by Django 6.0.5 on 2026-07-12 22:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='marca',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='mecanico',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='modelovehiculo',
            options={'ordering': ['marca__nombre', 'nombre']},
        ),
        migrations.AlterModelOptions(
            name='servicio',
            options={'ordering': ['nombre']},
        ),
        migrations.AddField(
            model_name='cliente',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ordenreparacion',
            name='mecanico_responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taller_api.mecanico'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicio',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='color',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='kilometraje',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='citaweb',
            name='estado',
            field=models.CharField(choices=[('SOLICITADA', 'Solicitada / Pendiente'), ('CONFIRMADA', 'Confirmada por el Taller'), ('EN_PROCESO', 'En proceso'), ('CANCELADA', 'Cancelada'), ('COMPLETADA', 'Asistió / Convertida en Orden')], default='SOLICITADA', max_length=20),
        ),
    ]
