# Generated by Django 6.0.5 on 2026-07-13 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller_api', '0003_alter_cliente_options_cliente_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citaweb',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADA', 'Aceptada'), ('REAGENDADA', 'Reagendada'), ('CANCELADA', 'Cancelada'), ('COMPLETADA', 'Completada')], default='PENDIENTE', max_length=20),
        ),
    ]
