# Generated by Django 6.0.5 on 2026-07-14 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller_api', '0004_alter_citaweb_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='citaweb',
            name='mensaje_taller',
            field=models.TextField(blank=True, default='', verbose_name='Mensaje del taller'),
        ),
    ]
