# Generated by Django 6.0.5 on 2026-07-14 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller_api', '0005_citaweb_mensaje_taller'),
    ]

    operations = [
        migrations.AddField(
            model_name='citaweb',
            name='fecha_confirmada',
            field=models.DateTimeField(blank=True, help_text='Fecha definitiva asignada por el taller', null=True),
        ),
    ]
